[project]
name = "distribution-analysis"
version = "0.1.0"
description = "Find quanaitzed model input/weight distribution."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets==4.0.0",
    "transformers==4.52.0",
]
